### ISSUE TITLE
v 1.3.0 exception

### ISSUE THREAD

**Issue by CrazyFlasher** [myflashlab/GoogleSignIn-ANE#18]
After I updated to 1.3.0 version, I receive this exception in android logs:
```
09-28 13:26:35.459	3659	5548	E	Parcel	Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
09-28 13:26:35.459	3659	5548	E	Parcel	java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
09-28 13:26:35.459	3659	5548	E	Parcel		at java.lang.Class.classForName(Native Method)
09-28 13:26:35.459	3659	5548	E	Parcel		at java.lang.Class.forName(Class.java:400)
09-28 13:26:35.459	3659	5548	E	Parcel		at android.os.Parcel.readParcelableCreator(Parcel.java:2517)
09-28 13:26:35.459	3659	5548	E	Parcel		at android.os.Parcel.readParcelable(Parcel.java:2471)
09-28 13:26:35.459	3659	5548	E	Parcel		at android.os.Parcel.readValue(Parcel.java:2374)
09-28 13:26:35.459	3659	5548	E	Parcel		at android.os.Parcel.readArrayMapInternal(Parcel.java:2727)
09-28 13:26:35.459	3659	5548	E	Parcel		at android.os.BaseBundle.unparcel(BaseBundle.java:269)
09-28 13:26:35.459	3659	5548	E	Parcel		at android.os.BaseBundle.getString(BaseBundle.java:992)
09-28 13:26:35.459	3659	5548	E	Parcel		at android.content.Intent.getStringExtra(Intent.java:6727)
09-28 13:26:35.459	3659	5548	E	Parcel		at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:336)
09-28 13:26:35.459	3659	5548	E	Parcel		at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1094)
09-28 13:26:35.459	3659	5548	E	Parcel		at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5822)
09-28 13:26:35.459	3659	5548	E	Parcel		at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5627)
09-28 13:26:35.459	3659	5548	E	Parcel		at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:176)
09-28 13:26:35.459	3659	5548	E	Parcel		at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3613)
09-28 13:26:35.459	3659	5548	E	Parcel		at android.os.Binder.execTransact(Binder.java:573)
09-28 13:26:35.459	3659	5548	E	Parcel	Caused by: java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
09-28 13:26:35.459	3659	5548	E	Parcel		at java.lang.Class.classForName(Native Method)
09-28 13:26:35.459	3659	5548	E	Parcel		at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
09-28 13:26:35.459	3659	5548	E	Parcel		at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
09-28 13:26:35.459	3659	5548	E	Parcel		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-28 13:26:35.459	3659	5548	E	Parcel		... 16 more
```
My manifest:
```xml
<?xml version="1.0" encoding="utf-8"?>
<application xmlns="http://ns.adobe.com/air/application/30.0">
  <id>com.crazyflasher.ktk</id>
  <versionNumber>1.2.0</versionNumber>
  <supportedProfiles>mobileDevice</supportedProfiles>
  <!--supportedProfiles>extendedDesktop</supportedProfiles-->
  <filename>Stickman Combats</filename>
  <name>
    <text xml:lang="en">Stickman Combats</text>
    <text xml:lang="ru">Stickman Combats</text>
  </name>
  <android>
    <containsVideo>true</containsVideo>
    <colorDepth>16bit</colorDepth>
    <manifestAdditions><![CDATA[
			<manifest android:installLocation="auto">

			  <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="26"/>

              <!--for internal videos-->
              <uses-permission android:name="android.permission.WAKE_LOCK" />
	          <uses-permission android:name="android.permission.DISABLE_KEYGUARD" />
              <!--for internal videos-->

              <!--Admob, Billing, AirNetworkInfo-->
              <uses-permission android:name="android.permission.INTERNET"/>

              <!--Admob, AirNetworkInfo-->
              <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

              <!--AirNetworkInfo-->
              <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>

              <!--Billing-->
              <uses-permission android:name="com.android.vending.BILLING" />
			  <uses-feature android:required="true" android:name="android.hardware.touchscreen.multitouch"/>

			  <application android:allowBackup="true" android:hardwareAccelerated="true" android:name="android.support.multidex.MultiDexApplication">

                <!-- Billing -->
		        <activity android:name="com.doitflash.inAppBilling.utils.MyPurchase" android:theme="@style/Theme.Transparent" />

                <!--Admob-->
                <activity>
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                    <intent-filter>
                        <action android:name="android.intent.action.VIEW" />
                        <category android:name="android.intent.category.BROWSABLE" />
                        <category android:name="android.intent.category.DEFAULT" />
                    </intent-filter>
                </activity>

                <!-- Admob -->
                <activity
                  android:name="com.google.android.gms.ads.AdActivity"
                  android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
                  android:theme="@android:style/Theme.Translucent" />

                <!-- GoogleSignIn -->
                <activity
                  android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity"
                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
                  android:excludeFromRecents="true" android:exported="false"/>

                <service android:name="com.google.android.gms.auth.api.signin.RevocationBoundService"
                    android:exported="true"
                    android:permission="com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION"/>

                <activity
                    android:name="com.google.android.gms.common.api.GoogleApiActivity"
                    android:theme="@android:style/Theme.Translucent.NoTitleBar"
                    android:exported="false"/>
                   
                 <!--Game Services-->
                 <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ 531279289872"/>

                <!-- GoogleSignIn, Admob -->
                <meta-data
			        android:name="com.google.android.gms.version"
			        android:value="@integer/google_play_services_version"/>

              </application>
			</manifest>

		]]></manifestAdditions>
    <disableMediaCodec>true</disableMediaCodec>
  </android>
  <iPhone>
  </iPhone>
  <initialWindow>
    <title>Stickman Combats</title>
    <content>kill-the-king.swf</content>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <autoOrients>true</autoOrients>
    <aspectRatio>landscape</aspectRatio>
    <renderMode>direct</renderMode>
    <depthAndStencil>true</depthAndStencil>
    <softKeyboardBehavior>none</softKeyboardBehavior>
    <!-- required for 3D -->
    <systemChrome>none</systemChrome>
  </initialWindow>
  <icon>
             <image36x36>assets/icons/android/icon-36x36.png</image36x36>         <image48x48>assets/icons/android/icon-48x48.png</image48x48>         <image72x72>assets/icons/android/icon-72x72.png</image72x72>         <image96x96>assets/icons/android/icon-96x96.png</image96x96>         <image144x144>assets/icons/android/icon-144x144.png</image144x144>         <image192x192>assets/icons/android/icon-192x192.png</image192x192>     
  </icon>
  <description>
    <text xml:lang="ru"></text>
    <text xml:lang="en"></text>
  </description>
  <extensions>
    <extensionID>com.freshplanet.ane.AirNetworkInfo</extensionID>
    <extensionID>adobe.nativeExtension.dataShare</extensionID>
    <extensionID>com.myflashlab.air.extensions.billing</extensionID>
    <extensionID>com.myflashlab.air.extensions.admob</extensionID>
    <extensionID>com.myflashlab.air.extensions.google.signin</extensionID>
    <extensionID>com.myflashlab.air.extensions.gameServices</extensionID>

    <!--dependencies-->
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.arch</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.customtabs</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.v4</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.games</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.drive</extensionID>
  </extensions>
  <supportedLanguages>en ru</supportedLanguages>
</application>
```

All dependencies are the latest

**Comment by myflashlab** [comment]
first check this out: https://stackoverflow.com/questions/36309169/classnotfoundexception-for-signinconfiguration-when-signing-in-with-google

and then please double check if you have updated the dependency files? for example we have removed the googlePlayServices_authBase.ane to be included inside googlePlayServices_auth.ane so if you have forgotten to use the latest googlePlayServices_auth.ane as an example, you might be facing weird error messages. so, please check that again.

**Comment by CrazyFlasher** [comment]
Also I didn't turn on App signing.
Page looks like this:
![image](https://user-images.githubusercontent.com/1607138/46260696-e7ce0080-c4f1-11e8-90f1-a74f890398b3.png)

**Comment by CrazyFlasher** [comment]
Wow.. it doesn't matter if I set `options.gamesSignIn = false` or `options.gamesSignIn = true`
It doesn't throw this exception if I do not specify `options.requestScopes`!

**Comment by CrazyFlasher** [comment]
Sorry.. I fucked up...need to rest a little.
It was simple. This line should be inside `application` tag of manifest.
`<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ 531279289872"/>`
Solved. Sorry for bothering.

**Comment by CrazyFlasher** [comment]
1. Doesn't work
```
 var options:GSignInOptions = new GSignInOptions();
				   options.gamesSignIn = true; // set to true if you are working with Google Games Services ANE.

//				   options.requestIdToken = webClientId; // get the client ID of your server
				   options.requestServerAuthCode = webClientId; // get the client ID of your server

				   options.requestId = false;
				   options.requestProfile = false;
				   options.requestEmail = false;

				   // IMPORTANT: if you are not using Game Save Snapshots, you would not need GScopes.DRIVE_APPFOLDER
				   options.requestScopes = [
					   GScopes.GAMES, GScopes.DRIVE_APPFOLDER
				   ];

				   // and pass the object to the initialization method of the ANE
				   GSignIn.init(options);

				   // Then, add listeners
				   GSignIn.listener.addEventListener(GSignInEvents.SILENT_SIGNIN_SUCCESS, onSilentSignInSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.SILENT_SIGNIN_FAILURE, onSilentSignInFailure);
				   GSignIn.listener.addEventListener(GSignInEvents.SIGNIN_SUCCESS, onSignInSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.SIGNIN_FAILURE, onSignInFailure);
				   GSignIn.listener.addEventListener(GSignInEvents.SIGNOUT_SUCCESS, onSignOutSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.SIGNOUT_FAILURE, onSignOutFailure);
				   GSignIn.listener.addEventListener(GSignInEvents.REVOKE_ACCESS_SUCCESS, onRevokeAccessSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.REVOKE_ACCESS_FAILURE, onRevokeAccessFailure);
				   GSignIn.listener.addEventListener(GSignInEvents.REQUEST_PERMISSION_SUCCESS, onRequestSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.REQUEST_PERMISSION_FAILURE, onRequestFailure);

```

2. Works (but without game services)
```
var options:GSignInOptions = new GSignInOptions();
				   options.gamesSignIn = false; // set to true if you are working with Google Games Services ANE.

//				   options.requestIdToken = webClientId; // get the client ID of your server
				   options.requestServerAuthCode = webClientId; // get the client ID of your server

				   options.requestId = false;
				   options.requestProfile = false;
				   options.requestEmail = false;

				   // IMPORTANT: if you are not using Game Save Snapshots, you would not need GScopes.DRIVE_APPFOLDER
				   /*options.requestScopes = [
					   GScopes.GAMES, GScopes.DRIVE_APPFOLDER
				   ];*/

				   // and pass the object to the initialization method of the ANE
				   GSignIn.init(options);

				   // Then, add listeners
				   GSignIn.listener.addEventListener(GSignInEvents.SILENT_SIGNIN_SUCCESS, onSilentSignInSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.SILENT_SIGNIN_FAILURE, onSilentSignInFailure);
				   GSignIn.listener.addEventListener(GSignInEvents.SIGNIN_SUCCESS, onSignInSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.SIGNIN_FAILURE, onSignInFailure);
				   GSignIn.listener.addEventListener(GSignInEvents.SIGNOUT_SUCCESS, onSignOutSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.SIGNOUT_FAILURE, onSignOutFailure);
				   GSignIn.listener.addEventListener(GSignInEvents.REVOKE_ACCESS_SUCCESS, onRevokeAccessSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.REVOKE_ACCESS_FAILURE, onRevokeAccessFailure);
				   GSignIn.listener.addEventListener(GSignInEvents.REQUEST_PERMISSION_SUCCESS, onRequestSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.REQUEST_PERMISSION_FAILURE, onRequestFailure);
```

**Comment by CrazyFlasher** [comment]
Looks like the problem was, that I used wrong client ID.
There should be an ID of web client. Not Android one from google play console.

**Comment by myflashlab** [comment]
Thanks for the messages, so, it is working fine now? If I got it correctly, you are trying to sign in users in a way to be able to do serverside works and also use it with the GamesServices.

**Comment by CrazyFlasher** [comment]
Yes, it works now, thanks!
Yes, I am trying to sign in users in a way to be able to do serverside works and also use it with the GamesServices.
